### ISSUE TITLE
Adding a filter reverses the order of events in a batch

### ISSUE THREAD

**Issue by ghelyar** [Azure/diagnostics-eventflow#135]
With just an input and an output, when events are written to the input, the output gets them in the same order.

With an input, a global filter and an output, the output gets the events collection in reverse order.

With two filters, the events in the batch are in the correct order again.

This may be because FilterAction in DiagnosticsPipeline is using stacks rather than queues.

Is this intentional?

I tried to get a unit test repro of this but couldn't make it deterministic (it seems to be deterministic in my live code and events are exactly in reverse order). Here's the gist for as far as I got, using Moq:
https://gist.github.com/ghelyar/a105051589a8cca3ac2e846e0268fa3e

**Comment by karolz-ms** [comment]
@ghelyar thanks for the heads up. Yes, this is by design. The ordering of events in the EventFlow pipeline is not guaranteed, and not just because of the FilterAction. It is entirely possible that a whole batch of events will "pass" a batch of ones that were created earlier. This is just a consequence of parallel processing within the pipeline. The assumption is each event carries a timestamp and once all get to their destination(s), the (temporal) order is clear.

Do you have a scenario where ordering is important?

**Comment by ghelyar** [comment]
It was just relating to issue #134 for timestamp precision with regards to ordering. If order is not maintained and the timestamps are not currently very precise it makes it difficult to work out the order of events. I had hoped that the batch sequence number combined with the collection of events would allow ordering even if the timestamps were the same.

As an example where ordering is important, just using the stdout output with a single filter and piping to a file to get logs does not produce logs that can be easily followed, even with concurrency 1.

It's not a big deal, I have a workaround for the timestamp precision using a custom input and can order by timestamp easily with linq in a custom output, but it would have been nice to have been able to use the inputs and outputs provided out of the box.

**Comment by karolz-ms** [comment]
Good points. I think it makes sense to maintain the ordering if we can. Let me see if I can change the FilterAction to maintain the order of events it received.

**Comment by karolz-ms** [comment]
OK, now I remember why the FilterAction was implemented the way it is. I wanted to use a pool containers to store events to keep and the containers need to be thread-safe. But also, to re-use containers from the pool, I need to be able to clear them efficiently. Only ConcurrentStack from System.Collections.Concurrent satisfies all criteria.

A Clear() method has since been added to ConcurrentQueue .NET Core 2.0 https://github.com/dotnet/corefx/pull/15292 but I do not think it is worth it to target Core 2.0 just to consume this feature.

So I think I am inclined to leave it as-is for now. Thanks for understanding!
