### ISSUE TITLE
event correlation - any support for Activity

### ISSUE THREAD

**Issue by cperras** [Azure/diagnostics-eventflow#145]
Any suggestions for correlating events with EventFlow?

I tried to use EventFlow for an asp.net core (2.0) project. however, there doesn't seem to be any way to easily correlate requests (say with Activity, https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md). 

I see some api's support things like RelatedActivityID, but it appears these must be set explicitly; ideally ActivityId and Baggage would be read from an ambient Activity context and then added to an event's metadata. I would be open to doing this myself if you can point me in the right direction. Any help is appreciated.

thanks,
--craig

**Comment by karolz-ms** [comment]
Hi Craig, sorry for late reply!

Yes, it totally makes sense to capture ambient Activity Id, ParentId, Tags and Baggage, although I would probably make Tags and Baggage capturing optional.

But to do it well it would require a bit of surgery on the EventFlow core. The main concern is to capture ambient Activity data before the event enters the asynchronous EventFlow pipeline and the ambient data is lost. This means we would have to have some sort of filter/initializer with guaranteed thread affinity (ThreadAffiinityFilter?), one that kick in before the event goes into the pipeline. The relevant spot in code is this: https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Core/Implementations/DiagnosticPipeline.cs#L177 Once the event is posted to the InputBuffer block (via the TargetBlockObserver), the rest of processing is asynchronous and we do not have an opportunity to catch the Activity.

Let me know if this sounds too scary. I think yours is a great idea and we should definitively do it.

BTW, I do not know if you realize, but DiagnosticSource Activity and its Activity.Id has nothing to do with EventSource's ActivityId and RelatedActivityId. :) Sorry! The former is about cross-machine correlation; the latter is for correlating asynchronous Task causality (as in System.Threading.Tasks, a.k.a. .NET Task Parallel Library a.k.a. TPL) within a service process. EventFlow does capture the latter.

**Comment by cperras** [comment]
thanks. i could try to add some kind of filter, but the simplest way was to capture the Activity in TargetBlockObserver.OnNext (also SendAsyncToTarget, but that isn't used).  

it's pretty straightforward if i either add an Activity property to EventData, or add it to the payload. adding Activity to the metadata will be trickier, since it must be serialized to a string. i would much rather expose the Activity object, and let sinks handle it as they will.

will this work? if so, do you have a preference whether it's a first-class property of EventData, or do you want it to be added to the payload?

also, i can add a flag "EnableActivityTracking" to DiagnosticPipelineConfiguration if you like. however, i don't think the overhead of this feature will be high.

**Comment by karolz-ms** [comment]
I think you are on the right track. Here is a sketch of the design & implementation--let me know what you think:

1. I would keep the TargetBlockObserver as-is to ensure separation of concerns. TargetBlockObserver is an adapter that ties together the EventFlow's concept of health reporter and DataFlow TPL ITargetBlock and I would not add to its responsibilites.
2. I would introduce a concept of a filter that requires thread affinity. I suspect there will be more scenarios than just Activity tracking when this is a requirement. I would probably introduce an attribute for that (e.g. RequiresThreadAffinityAttribute)
3. In DiagnosticsPipeline I would allow filters with thread affinity only as part of global filters (not output-specific filters, because by the time the event goes to the sink, we are deep in DataFlow part of the pipeline and there is no thread affinity)
4. I would create a new class for handling input to the pipeline when thread affinity filters are used (e.g. ThreadAffinityFilterExecutor). This class would implement IObservable<EventData>, just like TargetBlockObserver, and would wrap the TargetBlockObserver. It would have a collection of thread affinity filters. Whenever a new event shows up, the executor would execute all its filters sequentially, and then post to TargetBlockObserver and the rest of the pipeline.
5. In the DiagnosticsPipeline constructor I would then check whether we have any thread affinity filters in the globalFilters collection. If yes, I would use the new ThreadAffinityFilterExecutor as the first element in the pipeline (but it would only execute thread affinity filters). The rest of the filters would be executed by FilterAction as it is today (only filters that do not require thread affinity). If no thread affinity filters are present, I would just use TargetBlockObserver as the first pipeline element.
6. Then I would implement ActivityInitializer as a thread affinity filter (actually, inheriting from IncludeConditionFilter, as I do not think that you'd want to add Activity properties to all events going through the pipeline--but if it is an IncludeConditionFilter, you have the flexibility) and add it to the Core NuGet package. 
7. I would add the Activity properties to the payload, not directly to EventData. EventData is deliberately a minimal interface to make it easier to cache instances of it in the future. Remember, the goal for EventFlow is to handle tens of thousands of events per second. How much data EventData has to carry, and how many memory allocations are made are of primary concern.
8. Then we need unit tests for 2-7.
9. ... and a documentation update for ActivityInitializer (in the filters section) and RequiresThreadAffinityAttribute (in the Extensibility section)

How scary does this sound? (LOL)

**Comment by SergeyKanzhelev** [comment]
@karolz-ms would it be faster just execute on the plan and migrate to Application Insights inputs?

**Comment by karolz-ms** [comment]
True, thanks @SergeyKanzhelev  I should have mentioned that Application Insights SDK has a built-in concept of TelemetryInitializer that can be used for Activity tracking, and, for HttpClient, Asp.Net Core, Service Fabric remoting, and soon EventHub queues, we even send/restore activity IDs over the wire automatically.

There is also documentation on how to track activities across services when using custom communication protocol https://docs.microsoft.com/en-us/azure/application-insights/application-insights-custom-operations-tracking

So if migrating to Application Insights SDK is an option, that might be the best choice.

**Comment by tedvanderveen** [comment]
So just to get it right, when using Trace logging and output to Event Hub, the ActivityId we set is not outputed?
```
        DiagnosticPipelineFactory.CreatePipeline("eventFlowConfig.json")

        If System.Diagnostics.Trace.CorrelationManager.ActivityId = Guid.Empty
            System.Diagnostics.Trace.CorrelationManager.ActivityId = Guid.NewGuid()
        End If

        System.Diagnostics.Trace.TraceWarning("EventFlow is working!")
```
(Sorry for the VB.Net code ;-) We are migrating an existing application to C# / .Net Core.

This is what I get in Event Hub:

`{"records":[{"level":"Warning","properties":{"Keywords":0,"ProviderName":"MonServer.exe","Message":"EventFlow is working!","EventId":0},"time":"2018-01-09T18:46:27.9272044+00:00"}]}`

**Comment by karolz-ms** [comment]
@tedvanderveen VB is just fine :-)

If your code (or something else) is setting ActivityID, the Trace input should just capture it. This is a missing functionality in EventFlow Trace input. I will open a separate issue for that.

This thread was about capturing Activity ID from the ambient context, implemented as a generic EventFlow filter. While this is something that would be quite useful, we do not have any immediate plans to do that. I am going to close this issue for now.
