### ISSUE TITLE
ElasticSearch 6.0

### ISSUE THREAD

**Issue by andersosthus** [Azure/diagnostics-eventflow#149]
Hi,

Today ElasticSearch 6 was released, and when NEST is released for ES 6, I'd like to add support for it to diagnostics-eventflow.

How would you like such a thing to be done? Do a major version bump on the Diagnostics.Eventflow.Output.ElasticSearch nuget ?

**Comment by karolz-ms** [comment]
What's the backward compatibility for NEST, can NEST 6 work with ES 5?

If yes, we can just bump up the minor version of the ES nuget. If no, then a major version bump is in order.

**Comment by andersosthus** [comment]
I'm not sure about the complete backward compatibility, but since the ES Output module only uses basic connection handling and bulking it will probably work with no issues even. But I'll look into the documentation once it's released.

**Comment by jeremysmith1** [comment]
I was able to upgrade the client with just a modification of a interface that was in use. 

The thing I would be concerned about is the 6.x way to only 1 type per index. Since the EventData object is the only type being sent, I do not see that as a problem. 

Updating to use ES connections pools would also be a good add. Would a PR be desired?

**Comment by karolz-ms** [comment]
@jeremysmith1 absolutely!

**Comment by karolz-ms** [comment]
thanks to @jeremysmith1 this is now implemented and published on Nuget.org
