### ISSUE TITLE
DiagnosticPipelineFactory.CreatePipeline caused run-time resource not enough error(0x800705AA)

### ISSUE THREAD

**Issue by tocalai** [Azure/diagnostics-eventflow#175]
1. .Net framework 4.7 with EventFlow.Core version: 1.1.4.0, console application 
2. Copy and paste sample code used factory  to create pipeline and input as relative .json file
3. Repeat running the application more than 5 times, the error occurred, and seems that the library occupied some resource belong to OS level(need further investigate). Only restart whole OS might solved the problem.

**Comment by yantang-msft** [comment]
What's your inputs, outputs? Also, 1.1.4.0 is also quite old, have you tried the latest version?

**Comment by tocalai** [comment]
Thank you for quickly response.
The EventFlow version(1.1.4.0) was default pulling by nuget for the target .Net framework.
We used "ETW" for input and "StdOutput" for ouput.
And according the research we have found that: 
The library will create new TraceEventSession for each time initial and keep running even the application was terminated.
And according the article: https://stackoverflow.com/questions/39980899/traceeventsession-usage-in-servicefabric-application-raises-insufficient-resourc
We guess that might caused the problem?

**Comment by yantang-msft** [comment]
@tocalai I confirm it could be an issue if the pipeline is not stopped gracefully. I.e, you need to make sure the diagnostics pipeline is disposed before you shut down the program. Could you give it a try and let us know if this solved your problem?

**Comment by tocalai** [comment]
@yantang-msft  Thank you for classified the problem for us. I have tested the library from 1.1.4 and 1.1.10, if I  stopped and disposal the pipeline resource gracefully, it should avoid the problem. Thank you very much.

**Comment by saitejkuralla** [comment]
DiagnosticPipelineFactory.CreatePipeline("eventFlowConfig.json") this pipline causes error when multiple async requests

 using (var pipeline = DiagnosticPipelineFactory.CreatePipeline("eventFlowConfig.json"))
            {
                Log.Logger = new LoggerConfiguration()
                    .WriteTo.EventFlow(pipeline)
                    .Enrich.WithProperty("Path", _sourcePath[(int)source])
                    .CreateLogger();
                LogOperations(information, type, propertyValues);
                Log.CloseAndFlush();

            }

**Comment by karolz-ms** [comment]
@saitejkuralla 

1. What is the call stack of the exception? (please click "View Details" in the un-handled exception popup to see it). This will also give you a clue as to what exactly the problem might be.
1. I do not think the exception has anything to do with async requests--looks like it is coming from EventFlow initialization code, before any events are processed. My guess would be you have multiple instances of the same service/process, trying to create a health report file in the same place, with the same name. You can use [CsvHealthReporter properties](https://github.com/Azure/diagnostics-eventflow#csvhealthreporter), esp. `logFileFolder` and `logFilePrefix` to place these files in different folders and/or use different names fore every instance.
1. If my guess is wrong and this is a different problem, please open a new issue rather than reusing this one.

Hope this helps!

**Comment by saitejkuralla** [comment]
@karolz-ms Yes , it looks like your guess is correct 
Since we are developing microservices multiple instances are accessing logger project.
Logger Project is common to all the API's.
Can you please help me to fix this issue.
(How to pass the Logfile folder and prefix dynamically ?)   


at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFileImp(String logFileFolder, Func`2 fileExist, Action`1 fileDelete, Action`2 fileMove)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFile(String logFileFolder)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.SetNewStreamWriter()
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.Activate()
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(IConfiguration configuration, IHealthReporter healthReporter)
   at Radian.MIOnline.CustomLogger.Output.MIInputSeriLogger.RadianCustomLogger(String information, LogType source, LogOperation type, Object[] propertyValues) in C:\microservices\Common\Radian.MIOnline.CustomLogger\RadianMIInputSeriLogger.cs:line 30
   at PolicyActivation.API.Infrastructure.Middleware.HttpResponseTime.<>c__DisplayClass4_0.<InvokeAsync>b__0() in C:\microservices\Services\PolicyActivation\PolicyActivation.API\Infrastructure\Middleware\HttpResponseTime.cs:line 64
   at Microsoft.AspNetCore.Http.HttpResponse.<>c.<.cctor>b__30_0(Object callback)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame.<FireOnStarting>d__197.MoveNext()

**Comment by karolz-ms** [comment]
Good question @saitejkuralla If you have a separate project for logging, I would suggest to just forget the configuration file (eventFlowConfig.json) and construct the EventFlow pipeline imperatively, that is use [`DiagnosticPipeline` public constructor](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Core/Implementations/DiagnosticPipeline.cs#L31) directly. 

Every major EventFlow class, including `CsvHealthReporter`, has a public constructor, so you can create it, set its properties as necessary, and then pass to `DiagnosticPipeline` constructor.

This way your Logger project can expose an API that takes parameters for things that are different between consumers (such as health reporter file location), and then creates the EventFlow pipeline accordingly. For more information on various pipeline elements see https://github.com/Azure/diagnostics-eventflow#eventflow-pipeline-element-types 

Hope this helps!

**Comment by chavi289** [comment]
We are facing the same issue if we have multiple instances of the App Service running and the eventflowconfig.json gets locked by one of the instance. Can we update EventFlow to access the file in 'Read' mode and not lock the file. What will be the best way to handle this kind of scenario?

**Comment by karolz-ms** [comment]
@chavi289 I am a bit surprised that you say `eventflowconfig.json` gets locked. This is a configuration file that should not be open for writing, it should be open with shared, read-only access. What makes you think this file is the culprit?

Note that @saitejkuralla confirmed the file that was causing trouble was the health reporter file, not the pipeline configuration file. That file must be open in exclusive-access, read-write (or write-only) mode because it is used to store EventFlow warnings and errors. One solution I am thinking about is to  optionally add a random suffix to the file name to allow different service instances to have their own file all in the same directory, but I would like to make sure we are solving the right problem, so please elaborate on what you are seeing.

**Comment by chavi289** [comment]
@karolz-ms  we see the following error when we enable stdoutputlogs fot App Service, when it is deployed with more than one instance. This issue never occurs with Single instance.
This error does talk about the CsvHealthReporter file being locked in the stack trace. 

Unhandled Exception: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.Win32FileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFileImp(String logFileFolder, Func`2 fileExist, Action`1 fileDelete, Action`2 fileMove)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.RotateLogFile(String logFileFolder)
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.SetNewStreamWriter()
   at Microsoft.Diagnostics.EventFlow.HealthReporters.CsvHealthReporter.Activate()
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(IConfiguration configuration, IHealthReporter healthReporter)
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(String jsonConfigFilePath)
   at BASF.PMBB.PlantMonitoring.UIService.Program.Main(String[] args)

Another thing which I have observed is, if I try to run two services together locally, each having its own eventflowconfig.json I see the same error about the eventflowconfig file being used by another process.

**Comment by saitejkuralla** [comment]
@karolz-ms : Still I am facing the same issue and couldn't able to resolve this.

Since I am using multiple instance it is trying to write data into the CSV file which is being used by another process. 
Can i disable the creation of health report if so could please share me the code.
Thank you.
@chavi289 Hope the issue is same for both of us. Please let me know if you resolved that issue.

**Comment by karolz-ms** [comment]
@chavi289 The call stack that you included confirms that the error is due to two instances of `CsvHealthReporter` writing to the same file. We can try to remedy this issue via random suffix added to the file name like I said above.

> Another thing which I have observed is, if I try to run two services together locally, each having its own eventflowconfig.json I see the same error about the eventflowconfig file being used by another process.

If the error is about eventflowconfig file, *it is not the same error*. Can you paste the exact error message and call stack, please?

@saitejkuralla The health reporter cannot be disabled. 

As of today, you can use [the `logFilePrefix` property of the `CsvHealthReporter` configuration](https://github.com/Azure/diagnostics-eventflow#csvhealthreporter) to give each instance of your service a unique name. This is somewhat awkward when using a configuration file, because the configuration file would be then different for each instance of the service, that is why I suggested you create the `DiagnosticPipeline` via code. [Application Inisghts input documentation](https://github.com/Azure/diagnostics-eventflow#application-insights-input) contains an example of how to instantiate EventFlow using code. I believe this is a better option for you if you have logging factored out into a separate project.

Having said that, I will try to implement the random suffix workaround today and that should largely avoid the problem. It would be an opt-in feature though.

**Comment by karolz-ms** [comment]
@chavi289 @saitejkuralla I have published a new version of EventFlow core package (1.5.2) that should help you with your scenario.

Please get that NuGet package and configure the health reporter so that `assumeSharedLogFolder` parameter is set to `true` https://github.com/Azure/diagnostics-eventflow#csvhealthreporter

Let us know if this change works for you--thx!

**Comment by saitejkuralla** [comment]
@karolz-ms It's working in my local. We are performing some load tests on it will update you once done.
Mean while I have a question. There is some random things logging in csv file. Can we avoid creating the random messages
You can see my screenshot below 
My configuration (Screen shot attached)

![image](https://user-images.githubusercontent.com/11627655/47218869-c6fb1b80-d3ca-11e8-826e-2f6737594c43.png)
![image](https://user-images.githubusercontent.com/11627655/47219011-33761a80-d3cb-11e8-9167-9e4215a1c671.png)

**Comment by chavi289** [comment]
@karolz-ms , thanks for providing a quick fix. However, we changed our code to use Imperative binding instead of eventflowconfig.json, however this should be helpful in the future.

**Comment by karolz-ms** [comment]
@chavi289 sounds good; let us know if you have any other questions

@saitejkuralla the thing that you see in the file is not "random thing", it is [a Unicode byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark). You are right though that it should not be there. I have opened a separate issue to track this. Thanks for the report!

**Comment by karolz-ms** [comment]
@saitejkuralla just FYI, the issue with BOM being written to the health reporter file is now fixed. Also, I have just published another update (EventFlow core package 1.5.4) that should prevent the health reporter file from being created at startup--it should only be created if there are actual health reports. Please give it a try--hope this helps.

**Comment by saitejkuralla** [comment]
Thanks a Lot @karolz-ms both the issues got fixed.
