### ISSUE TITLE
How to configure for ASP.NET 4.x application?

### ISSUE THREAD

**Issue by jsturtevant** [Azure/diagnostics-eventflow#199]
There are examples on how to configure with `Asp.net Core` and `Service Fabric`. 

How do you configure this for an ASP.NET application that is not Service Fabric or core?  Where do you start the the Diagnostic Pipeline?  Would it be in the `global.asax.cs`?

**Comment by karolz-ms** [comment]
Yes, `global.asax.cs` would be the logical place. Just make sure that you dispose of the pipeline on application shutdown.

**Comment by jsturtevant** [comment]
Is there anything to consider if the application doesn't exit gracefully?

**Comment by jsturtevant** [comment]
Thanks for the responses.  Do you know how that works in the case of Windows Containers?  Is it 8 ETW listeners per container or per host OS?  If the ETW instance is per container would removing the container clean up the listeners?

**Comment by karolz-ms** [comment]
My understanding is that ETW provider tracking does not work inside Windows Containers at all. 

Just want to make sure: you are aware that ETW != EventSource? And that you can track EventSources (or DiagnosticSources) all day long from inside Windows Containers (in-proc) (Linux containers work too)?

Why are you interested in ETW tracking?

**Comment by jsturtevant** [comment]
I guess I am not aware they are seperate.  The [docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netframework-4.7) on EventSource say:

> Provides the ability to create events for event tracing for Windows (ETW).

I was looking at ways to get the IIS logs out of the container. Or when using EventSource logging. [Service Monitor had implemented an ETW listener](https://github.com/Microsoft/IIS.ServiceMonitor/pull/13) inside a container though looks like it was reverted.

**Comment by karolz-ms** [comment]
Yeah, sorry, the docs are misleading. Exposing event method calls as ETW events is one of the features of EventSource, but these event methods can be also intercepted using other means, [EventListener](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener) in particular (which, BTW, also has bad docs IMO, because its main purpose is to intercept events from EventSources, and not to "enable and disable events from event sources" as the docs say). 

Anyway, I double checked with expert and it turns out that ETW tracking from within Windows containers is possible, but the functionality is limited. You can track user-mode providers, but not kernel-mode providers, which precludes things like CPU and context switches, so detailed profiling is not possible. 

That said, if you are interested in getting IIS logs from a container, I do not think ETW is the way to go. I would try to use a volume mount, make IIS write to that volume, and use something like logstash or fluentd to read the logs and send them where they need to go.

**Comment by jsturtevant** [comment]
Thanks for the detailed responses.  I have also been looking at the logstash/fluentd solution as well.

**Comment by vancem** [comment]
Just FYI, 6 months or so ago, the operating systems people did the work to make the most important Kernel ETW events work inside a (argon) windows container.    Thus you can collect traces that have user mode ETW as well as kernel mode ETW inside a container just as if it were a Virtual or Physical machine.   

In particular tools like WPR should work.   I don't have much direct experience here, but that is my understanding.
