### ISSUE TITLE
Cannot install nuget package Microsoft.Diagnostics.EventFlow.Inputs.Etw 1.3.0 to a project targeting .NET Framework

### ISSUE THREAD

**Issue by dvoits** [Azure/diagnostics-eventflow#212]
How to reproduce:

1. In Visual Studio Enterprise 2017 Version 15.7.1 I create new solution and project using template "Console App (.NET Framework)", and choose .NET Framework 4.6
2. Use Nuget Package Manager to install package _Microsoft.Diagnostics.EventFlow.Inputs.Etw_ 1.3.0  with dependency behavior "Highest".

Observed: Package Manager fails to install the package with following error:

> Could not install package 'Microsoft.Extensions.Configuration.Abstractions 2.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Expected: The package successfully installed to the project.

Same issue happens for other .NET Framework versions as well.

**Comment by karolz-ms** [comment]
@dvoits thank you for reporting this issue

Microsoft.Extensions.* packages from 2.x series are not compatible with .NET Framework 4.6.x  You should stick to the 1.x series of these and not use "highest" dependency behavior.

We should update EventFlow Core package definition to indicate it can only work with Microsoft.Extensions.* 1.x series when targeting .NET 4.5 and .NET 4.6. Let's keep this issue open until this happens. Thanks again for reporting.

**Comment by karolz-ms** [comment]
TODO: publish Core Nuget package version 1.4.1

**Comment by karolz-ms** [comment]
Core package 1.4.1 that should address this issue has been published

**Comment by Almulo** [comment]
So... If I already have a working .NET 4.6 application with a ton of references to Microsoft.Extensions 2.x packages (most of them as per the ASP.NET Core template for Service Fabric), then I'm out of luck and cannot use EventFlow at all? Unless I downgrade all those dependencies? Which sounds like a lot of work and uncertainty...

That's unfortunate considering EventFlow with EventSource is the suggested way to aggregate and pump events through Service Fabric :S I guess we're stuck with good ol' logging, for the time being?

**Comment by karolz-ms** [comment]
@Almulo there are a couple of options when creating a new SF application.

If you want to stay with .NET 4.6/4.6.1, you can use ASP.NET Core 1 instead of ASP.NET Core 2. This option is not available by default because the latest version of VS does not install .NET Core 1.1 by default, but it can be enabled via VS Installer. Once ASP.NET Core 1.1 is added to your VS installation, you can choose to target that version of ASP.NET from the dropdown at the top of "New ASP.NET Core Web Application" dialog, which shows up after "New Service Fabric application" dialog.

Alternatively you can target .NET Core 2.0 _framework_, which is the newest and best .NET implementation we have. The main problem with SF and this framework version is that standard Azure VM images do not have .NET Core 2.0 installed (YET). So you need to either:
- build your app as standalone (meaning, the FX is included in the package--this is SF template default), which results in very big app packages, or
- use a custom VM image for your SF cluster

For more info on .NET Core 2.0 and Service Fabric see https://blogs.msdn.microsoft.com/maheshkshirsagar/2018/03/27/running-asp-net-core-2-0-web-application-on-windows-azure-virtual-machine-scaleset-vmss/ and https://github.com/Azure/service-fabric-issues/issues/500

Hope this helps!
