### ISSUE TITLE
.NET Framework application crashes if uses EventFlow pipeline with ETW input 1.3.0

### ISSUE THREAD

**Issue by dvoits** [Azure/diagnostics-eventflow#213]
How to reproduce:
1. In Visual Studio Enterprise 2017 Version 15.7.1 I create new solution and project using template "Console App (.NET Framework)", and choose .NET Framework 4.6.
2. Use Nuget Package Manager to install package Microsoft.Diagnostics.EventFlow.Inputs.Etw 1.3.0 with dependency behavior "Lowest".
3. Add new file "eventFlowConfig.json" to the project; set its property "Copy to Output Directory" to "Copy always".

File content:

```json
{
  "inputs": [
    {
      "type": "ETW",
      "providers": [
        {
          "providerName": "Microsoft-Extensions-Logging"
        }
      ]
    }
  ],
  "filters": [],
  "outputs": [    
  ],
  "schemaVersion": "2016-08-11",
  "extensions": []
}
```

4. Edit `Program.cs`:

```C#
static void Main(string[] args)
{
    using (var pipeline = Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline("eventFlowConfig.json"))
    {
        Console.ReadKey(true);
    }
}
```

5. Run the program.

**Observed**: The program crashes with an unhandled exception:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at Microsoft.Diagnostics.EventFlow.DiagnosticPipelineFactory.CreatePipeline(String jsonConfigFilePath)
   at EventFlowETW2.Program.Main(String[] args) in c:\users\dmitry\documents\visual studio 2017\Projects\EventFlowETW2\EventFlowETW2\Program.cs:line 13
```

**Expected**: The program ends with error "DiagnosticPipelineFactory: 'outputs' configuration section is empty"

**Comment by dvoits** [comment]
This works for .NET Framework 4.6.1 though.

**Comment by karolz-ms** [comment]
@dvoits thank you for taking time to report this issue

Updating NuGet package reference to Microsoft.Diagnostics.Tracing.TraceEvent to latest version (2.0.11 as I am writing this) should eliminate FileNotFoundException at shutdown.

I will keep this issue open to remind us to update this EventFlow ETW input package dependency at the earliest convenience.

As to .NET 4.6 vs. 4.6.1, at this point there is really no good reason to target the original 4.6 framework because of many bug fixes and improvements that went to 4.6.1. That is why I am inclined to say just don't target 4.6.

**Comment by dvoits** [comment]
For the .NET 4.6.1 application, I have updated package Microsoft.Diagnostics.Tracing.TraceEvent from 2.0.6 to 2.0.11 and it works now! @karolz-ms, thanks a lot!

**Comment by karolz-ms** [comment]
TODO: publish ETW input package version 1.3.1

**Comment by karolz-ms** [comment]
Package 1.3.1 has been published

**Comment by saitejkuralla** [comment]
@karolz-ms I have a Diagnostic even flow logger  project and is referenced in .Net framework 4.6.2 and I am getting an error as below .
![image](https://user-images.githubusercontent.com/11627655/47702945-8a3de880-dc44-11e8-9592-f3f1013c4a99.png)

My thought on this is It is not searching the eventflowconfig.Json file in bin folder , instead it is searching in the root folder of the .net framework project.
Kindly suggest me for a fix.
Thank you.

**Comment by karolz-ms** [comment]
@saitejkuralla We can look into this, but for future reference, please open a new issue instead of adding comments to existing, closed issue. I have just opened one for you as an example. 

Your problem has nothing to do with the issue described here and it just makes it more confusing for people that might encounter the original issue and look for guidance, so let's keep them separate.

**Comment by saitejkuralla** [comment]
@karolz-ms Sure, Thank You.
