### ISSUE TITLE
Change in eventsource seems to kill ETW listener

### ISSUE THREAD

**Issue by shacal** [Azure/diagnostics-eventflow#240]
I have service fabric cluster, and every node has service that uses eventflow to send details to custom output (copy of eventhub but more usable json format). ETW provider does not pickup changes on manifest and does not post anything to output providers.

Restarting does not help, restarting machine helps. And I have cleanup enabled for ETW provider.

**Comment by karolz-ms** [comment]
@shacal can you elaborate on what you mean by "ETW provider does not pick up changes on manifest"? 
  - what exactly are you changing about your application/EventFlow configuration?
  - what you *expect* to happen vs. what is actually happening?
  - what exactly is the configuration for the EventFlow ETW input?
  - how many instances of the service use that ETW input on a single cluster node, and in general, how many instances of your service do you have on the cluster?

**Comment by shacal** [comment]
Nothing gets changed in eventflow. But the eventsource gets new events with ID's.
Example: I have one eventsource provider that is shared by two services. Both of services are running in same node. When I add new event to that event source, and upgrade service A, new event is not picked up by eventflow service. And when I upgrade service B - so both are now using the same version of eventsource, olld events are dropped.

Im expecting that when I add more events in shared eventsource, service that is hookin eventflow to ETW input will update manifest and starts sending the new events introduced.

>
      "type": "ETW",
      "sessionNamePrefix": "Telemetry-Etw",
      "cleanupOldSessions": true,
      "reuseExistingSession": true,
      "providers": [
        {
          "providerName": "Microsoft-ServiceFabric",
          "level": "Informational",
          "keywords": 4611686018427387912
        },
        {
          "providerName": "Microsoft-ServiceFabric-Services",
          "level": "Informational"
        }

I have one service per node (instance count: -1), for ETW input.
And two services that are writing using eventsource (10-50 instances)

**Comment by karolz-ms** [comment]
Thanks for the explanation @shacal 

First, if you are setting `reuseExistingSession: true`, the ETW session that ETW input uses will not be closed when the input is disposed of (e.g. as a result of the service shutting down). That is why the behavior that you are seeing persists even when the service is restarted. It is by design.

My understanding of what you are trying to do is:

1.	You have an EventSource E that is used by services A and B, and a monitoring service M that is using EventFlow ETW input to monitor source E.
2.	You **change the definition of E** used by service A and upgrade (redeploy) the service A. The cluster node is now running with **two different definitions of E**.
3.	You then change the definition of E used by service B to match the definition of the E used by service A and redeploy service B. The cluster node now has a consistent definition of E, but **it is different from the definition that the monitoring service M saw at the beginning of the scenario**.
4.	You expect all these changes to E to be picked up by monitoring service M, **within the same ETW monitoring session that M maintains**.

I am not sure if the scenario above is supported by ETW and/or the TraceEvent library that EventFlow ETW input is using. @vancem @brianrob can you guys confirm/deny? Thx!

**Comment by vancem** [comment]
Responding @karolz-ms question:   

First lets state the question (as I understand it)

To make events efficient (compact) some information called meta-data is not send along with each event, but gets communicated some other way.  This information is needed to decode a particular event data blob into a list of key-value pairs.  

The question is can the infrastructure handle adding new events (and thus need new/more meta-data) as the system. runs.

In a word: YES.    However as you might expect this is not a well tested area, and there are multiple layers of software involved any one of which could be causing grief.   Thus it would not surprise me to find bugs (but they are bugs, can should be straightforward to fix once found).  

The first step is to determine exactly how the meta-data is communicated from the provider to the consumer (event parser) (basically how should it work?)    

@karolz-ms : do we use the self-describing ETW in these EventSources (do they use Write<T> or use the SelfDescribingETW option when creating the EventSource?)   I am assuming NO.

If that is true, then the meta-data is communicated via special 'Manifest' events that EventSource itself generates.  

The next question is how the parser works.   I am going to assume it is using TraceEvent and its DyanmicTraceEventParser.   @karolz-ms  can you confirm?

Assuming it is and assuming you are using the latest nuget package, then I would have expected the scenario 'just work' for the case of adding new events or adding new fields to existing events AT THE END).    It is important that you should NOT remove events from an EventSource (until there is NO (old) code using it).   Basically TraceEvent is constantly listening for manifest events and has a notion of the manifest being 'better' (having more events in it), and it chooses the 'best' one.  

Now having said this, bugs are always possible.   But it *should* work and with some debugging effort we can figure out why it is not and find a fix.

**Comment by karolz-ms** [comment]
@vancem thanks for comprehensive reply, much appreciated. To answer your questions:

 - I assume self-describing events are NOT used since the developer is talking about "adding new event to the EventSource"
  - Yes, the EventFlow ETW input is using `DynamicTraceEventParser`: https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Inputs.Etw/StandardTraceEventSession.cs#L90

I will try if I can reproduce the problem in-house and outside of Service Fabric environment (which is, I believe, irrelevant in this case) and will let you know what I find. Thanks again!

**Comment by shacal** [comment]
Thanks guys, we are in day 8 after global launch and a bit busy atm. Ill try to change the session boolean and see if there is any affect.

I see Manifest events and I actually did not expect them to go thru, and I'm filtering them in my eventhub output.

**Comment by shacal** [comment]
Hi all!
I found that one event interface changed from int to int64, that seems to be breaking manifest and confusing all this.
I changed the name of event source and I have old and new now and I update all services to get rid of old name.

Any idea why "manifest" event is not filtered, or should it be filtered out?

**Comment by karolz-ms** [comment]
Glad you were able to get your program working.

Well, ManifestData event is just part how EventSource, or more generically, ETW providers that use dynamic manifests work. Should it be filtered out? Possibly... but you can also argue it helps with debugging, so I am not really sure. I am inclined to leave it as-is unless others find it annoying.

So can I assume this issue is resolved?

**Comment by shacal** [comment]
Thx for all guys, have now much better understanding the behaviour.
Filter boolean would make sense, as upscaling hundreds of servers and flood of ”cryptic” manifest data makes ppl just wondering. But, easy to filter out anyway with flow.

Ill close this issue, as I consider it resolved and user error.
