### ISSUE TITLE
Performance SeriLog as input 

### ISSUE THREAD

**Issue by saitejkuralla** [Azure/diagnostics-eventflow#297]
Hi @karolz-ms 

We are facing performance issue while logging with serilog as Input
could you please suggest the way to increase the performance. It is taking almost half a second to log my data.
And I am using my custom logger as out put which is log4net file appender 
![image](https://user-images.githubusercontent.com/11627655/49729486-a8632380-fc9b-11e8-8155-0840df1135d7.png)

Stats 
![image](https://user-images.githubusercontent.com/11627655/49729673-23c4d500-fc9c-11e8-98db-063c246eadbb.png)

**Comment by karolz-ms** [comment]
@saitejkuralla what is your expectation about the performance, and is it about **latency** (e.g. you expect the event to arrive to the output within `x` milliseconds from the moment it is logged, but it takes more than 0.5 second) or **throughput** (e.g. you are expecting EventFlow to process `x` thousands of events/second, but it is only processing tens or hundreds)?

EventFlow is optimized for throughput, not latency. That is, it can handle thousands of events/second, but each individual event may take a while to be processed. I suspect what you are seeing is the effect of the EventFlow batching logic. EventFlow will batch events together in order to increase throughput. It will wait for enough events to come to form a full batch (100 events by default), but it will time out the wait and release incomplete batch for processing if fewer events come within the timeout period. The default timeout is 500 ms. So if your code produces a single event, then waits for it to reach the output, you will get one event per about half a second going through EventFlow.

You can tweak this behavior through [pipeline settings](https://github.com/Azure/diagnostics-eventflow#pipeline-settings), but keep in mind, the EventFlow goal is throughput, not latency. Latency may be reduced by lowering the `maxBatchDelayMsec` parameter, but there will always be *some* overhead latency.

If, after reading through this, you still think there is some performance issue with EventFlow, please run your code under a profiler (e.g. the one that comes with Visual Studio) and share with us both the profiling results and the source code that demonstrates the problem.

Hope this helps!

**Comment by vbkattamudi** [comment]
Hi @karolz-ms,

This is behalf of @saitejkuralla 

We did the necessary changes as per your inputs in local it is taking to write logs between 40-100 milliseconds but on server it is taking 500-600 milliseconds. 
Server configuration is better than local environment.
Did we miss anything?
Can you please help us how to resolve the issue

Thank you,
VBKattamudi

**Comment by karolz-ms** [comment]
@vbkattamudi @saitejkuralla can you describe what latency do you expect to achieve and **why is it important for you**?

As I mentioned before, it would be great if you could share some code that illustrates the problem, so I can understand better how exactly the numbers you quote are produced.

**Comment by saitejkuralla** [comment]
Hi @karolz-ms,
 
Please find the attachment of the sample project . 
Before integrating with diagnostics we used the log4net project it took less than 4-5 milli seconds to log the details to the log file.
But now it is taking almost 0.5 seconds for each log to write into the file.
We are expecting Latency should be less than 5-10 ms
Please help us to resolve this issue
[SampleLogApplication.zip](https://github.com/Azure/diagnostics-eventflow/files/2675900/SampleLogApplication.zip)

**Comment by karolz-ms** [comment]
@saitejkuralla looks like you are creating and destroying an EventFlow pipeline every time you log something. This is both unnecessary and very costly. You should create the pipeline just once, when the application is starting, and make sure you destroy it when the application is shutting down.

One possible way to do so for an ASP.NET Core application is documented here: https://github.com/Azure/diagnostics-eventflow#microsoftextensionslogging

**Comment by saitejkuralla** [comment]
@karolz-ms if we are not creating pipeline just once it is creating the log only once.
So what we have done was this 
![image](https://user-images.githubusercontent.com/11627655/49991359-d485e980-ffa6-11e8-8cc4-6e544701bbcb.png)
And it solves our performance issue but only one concern is the logs are not logging in order .

**Comment by karolz-ms** [comment]
@saitejkuralla EventFlow does not guarantee that events will arrive at the output in the same order as they were logged. Relaxing this requirement allows EventFlow to process data in parallel, taking advantage of all computing resources the machine has.

Events have Timestamp property, so you can always know when it was logged and sort them in order of creation (assuming of course that, in multi-machine case, clocks are reasonably close).

Let us know if you have further questions

**Comment by saitejkuralla** [comment]
@karolz-ms Thank you very much for you support .we had done initialization in a wrong way , rectified and resolved the issue.
