### ISSUE TITLE
Message size in EventHub

### ISSUE THREAD

**Issue by Sbou** [Azure/diagnostics-eventflow#302]
Hi,

I use eventfow with Microsoft Logging as input and EventHub as output. 

I have an issue with logs containing exception. 
If the exception contains inner exceptions, the stack trace is really huge and the EventHub message size is too large. 

So some logs are missing. 
Is it possible to avoid to serialize all the exception object ?

Thank you

**Comment by karolz-ms** [comment]
@Sbou could you share an example (code) that illustrates the problem?

The EventHub output has logic that limits the size of a single message by breaking the batch into smaller parts. A single message limit is around 200 KB. Are you saying your application can produce an exception which exceeds 200 KB when serialized via toString()?

You can always write [a custom filter](https://github.com/Azure/diagnostics-eventflow#filters-1) that deletes properties from events passing through EventFlow pipeline, but maybe there is a better option, so an example would help.

**Comment by Sbou** [comment]
Thanks for your answer.
I checked the source code and analyez our issue.

Our exception is a "StorageException" when we use an Azure Blob storage.
There are two issues.
The first is a circular exception with the "RequestInformation" property which contains the same exception (This error should have triggered a log in the HealthReporter but we have nothing).

So, we tried to serialize this exception outside of EventFlow with this settings:
 ReferenceLoopHandling = ReferenceLoopHandling.Ignore

We don't have an error but the serialized string is huge.
The second issue is the "TargetSite" property of type System.Reflection.MethodBase. The serializer serialize all this object cluster.
It could be interesting to create a JsonConverter to reduce the serialization of System.Reflection objects.

Thank you

**Comment by karolz-ms** [comment]
@Sbou, very good analysis, very helpful, thank you!

We should probably make `ReferenceLoopHandling.Ignore` a default setting for EventFlow. I will keep this issue open till this change is made.

I was also wondering why JSON.net would try to serialize the request exception property-by-property, including TargetSite etc. Turns out it might be at least partially due to a bug in JSON.net See [first answer to this question on StackOverflow](https://stackoverflow.com/questions/52633377/serializing-an-exception-return-a-very-large-json). Could you maybe upgrade to JSON.net ver 12.0.1 or newer and see if it makes things better (smaller)?

**Comment by karolz-ms** [comment]
The EventHub package 1.4.1 or newer will ignore circular references during JSON serialization
