### ISSUE TITLE
Trouble using Elasticsearch output

### ISSUE THREAD

**Issue by BastiaanLouis** [Azure/diagnostics-eventflow#318]
I'm probably doing something wrong using the elasticsearch output so I need some help.
Trying to listen to EventCounter events based on an EventSource. The output should be piped to both console and elasticsearch. The console output seems fine but the healthreporter gives me the following issue from the elasticsearch output:

> 2019-04-19 09:23:00Z,Microsoft.Diagnostics.EventFlow.Output,Error,"ElasticSearchOutput: The expected event property 'Name' is either missing from event data, or its value is invalid"

Used eventsource with counters:
```csharp
[EventSource(Name = "My-Events")]
public sealed class CustomMetricsEventSource : EventSource
{
  private readonly EventCounter _methodDurationCounter;
  
  private readonly Dictionary<string, EventCounter> _dynamicCounters =
    new Dictionary<string, EventCounter>();
  
  public static CustomMetricsEventSource Log = new CustomMetricsEventSource();
  
  public CustomMetricsEventSource()
  {
    _methodDurationCounter = new EventCounter(nameof(_methodDurationCounter), this);
  }
  
  public void ReportMetric(string name, float value)
  {
    if (!_dynamicCounters.TryGetValue(name, out EventCounter counterInstance))
    {
      counterInstance = new EventCounter(name, this);
      _dynamicCounters.Add(name, counterInstance);
    }
    counterInstance.WriteMetric(value);
  }
}
```
Configuration is handled through the following config file:
```json
{
  "inputs": [
    {
      "type": "EventSource",
      "sources": [
       {
         "providerName": "My-Events",
         "eventCountersSamplingInterval": 1
       }
      ]
    }
  ],
  "outputs": [
    {
      "type": "ElasticSearch",
      "indexNamePrefix": "myIndex",
      "serviceUri": "https://localhost:9200",
    },
    {
      "type": "StdOutput"
    }
  ],
  "schemaVersion": "2016-08-11"
}
```
output of the console seems fine
![image](https://user-images.githubusercontent.com/24946645/56418859-8e180280-6298-11e9-98a9-fb2e2c472c99.png)

While debugging to find out what happens I've been looking at the code in EventDataExtensions and especially the method ExtractEventCounterPayloadData. Although this is part of the input, it seems that in here all properties of the payload of the EventWrittenArgs are mapped to the EventData. In the second step a metric mapping is also added to the eventData because there is no filtering in here to skip the metadata. Because the Name of the counter is one of the payload properties, it is also mapped which results in a try to convert the value to a double. Because of that failure, ouputting to elastic seems to fail.
In addition, when adding additional metadata fields in the eventflowConfig.json (e.g. the name of the machine firing the event) these metadata fields are also part of the payload and because of that in the list of metrics which resulted in failures as described above.

Am I doing something wrong or is this a bug? In case of the second, can you point me a direction in how to solve it? Maybe I can create a PR for that.

Thx!

**Comment by karolz-ms** [comment]
@BastiaanLouis thank you for reporting this issue. I believe we have a bug in [`ExtractEventCounterPayloadData`](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Inputs.EventSource/EventDataExtensions.cs#L94) in the sense that we should not add metric metadata (mapping) if the payload property value is not a number (a `double` value). So I think the fix would be to add a check there and only add metric metadata for things numeric.

We should also verify the metadata [in the EventCounter test](https://github.com/Azure/diagnostics-eventflow/blob/master/test/Microsoft.Diagnostics.EventFlow.Inputs.Tests/EventSourceInputTests.cs#L232). 

If you want to take a stab at fixing this, it would be very much appreciated. I can help you getting things merged and published on Nuget.org. If not, we can get this fixed in the next week or so, most likely.

Thanks again!

**Comment by karolz-ms** [comment]
@BastiaanLouis Microsoft.Diagnostics.EventFlow.Inputs.EventSource 1.4.5 package is now published on nuget.org. Please give a try and let us know if it fixes this issue
