### ISSUE TITLE
Collecting performance counters from other process into counters of current process

### ISSUE THREAD

**Issue by dmytro-ielkin** [Azure/diagnostics-eventflow#36]
Hi team!

We're trying to collect performance counters from other process and send it via EventFlow of the current process of a console application that will act as an agent (or even in a test).

To achieve this we replace counter and category names before creating diagnostic pipeline. You can find code sample and configuration in the attached archive.

We assume that our attempts fail because performance counters of current process are read only (as per [ProcessInstanceNameCache.cs](https://github.com/Azure/diagnostics-eventflow/blob/master/src/Microsoft.Diagnostics.EventFlow.Inputs.PerformanceCounter/ProcessInstanceNameCache.cs) file

Could you please have a look and let me know if our approach is feasible or should we try implementing custom input for this?

[EventFlowPOC.zip](https://github.com/Azure/diagnostics-eventflow/files/717211/EventFlowPOC.zip)

P.S. Sorry if this is wrong place to post such questions but didn't find other places to ask.

**Comment by karolz-ms** [comment]
@dmytro-ielkin, as you noticed, the PerformanceCounterInput was designed to monitor performance counters of the process that is running EventFlow. That is why it has the code to discover the performance counter instance name that corresponds to the current process.

If you intend to monitor performance counters from other processes, this process-to counter instance mapping is going to be either unnecessary or different :-) I think you will have much more success implementing this as a separate input instead of trying to trick the current PerformanceCounterInput into monitoring performance counters from other processes. Implementing an input is not very hard; it is basically just an IObservable<EventData>, and you can re-use as much of the current PerformanceCounterInput code as necessary.

An alternative would be to enhance the PerformanceCounterInput to support both current process counters and other process counters (or counters without an instance name). If you are willing to go down that path and submit a PR, awesome. Note though that this would require thinking through necessary changes to the input configuration, as well as working out a practical way to find the right counter instance in case of multiple processes using the same counter category and name. We could also scope that scenario out and only support no-instance counters. Either way there is some design work to be done up front and agreed on. If you just need to get something working for your system, a custom input will get you there much faster.

Let me know if this makes sense and thanks for trying out EventFlow.

**Comment by dmytro-ielkin** [comment]
Hi,

For now we'll go with implementing our own input but we will consider submitting PR later when we get more into the inner workings on EventFlow.

And thanks a lot!

**Comment by karolz-ms** [comment]
OK, have fun!
